#!/usr/bin/python3

import amulet
import requests
import unittest


class TestCharm(unittest.TestCase):
    def setUp(self):
        self.d = amulet.Deployment()

        self.d.add('snmpd')
        self.d.expose('snmpd')

        self.d.setup(timeout=900)
        self.d.sentry.wait()

        self.unit = self.d.sentry['snmpd'][0]

    def test_service(self):
        pass